/**
 * Synthetic demo provider directory.
 * Explicitly marked as demonstration data — not live hospital availability.
 */

export const DEMO_LAST_UPDATED = '2026-09-27T06:30:00.000Z';
export const DEMO_LAST_UPDATED_LABEL = '27 Sep 2026, 09:30 EAT';
export const DEMO_DATA_SOURCE = 'Synthetic provider data — for demonstration only';

export const SYNTHETIC_PROVIDERS = [
  {
    id: 'prov-nbi-cardio-01',
    facility_name: 'Nairobi Heart Care Demo Clinic',
    facility_type: 'Specialist clinic',
    location: 'Westlands, Nairobi',
    county: 'Nairobi',
    specialties: ['cardiology'],
    specialist_name: 'Dr. Amina Otieno',
    availability_status: 'Reported available',
    availability_note: 'Demo schedule shows weekday morning slots.',
    appointment_required: true,
    referral_required: false,
    contact_information: 'Demo contact: +254 700 000 101',
    instructions: 'Call ahead to confirm a demo appointment slot. Bring a national ID if visiting in person.',
  },
  {
    id: 'prov-nbi-cardio-02',
    facility_name: 'Ridgeway Cardiology Demo Centre',
    facility_type: 'Hospital outpatient',
    location: 'Kilimani, Nairobi',
    county: 'Nairobi',
    specialties: ['cardiology'],
    specialist_name: 'Dr. Samuel Kariuki',
    availability_status: 'Limited availability',
    availability_note: 'Demo data shows referral preferred for new patients.',
    appointment_required: true,
    referral_required: true,
    contact_information: 'Demo contact: +254 700 000 102',
    instructions: 'Ask your GP for a referral note before booking. This is synthetic demo guidance only.',
  },
  {
    id: 'prov-nbi-derm-01',
    facility_name: 'Skin & Wellness Demo Clinic',
    facility_type: 'Specialist clinic',
    location: 'Lavington, Nairobi',
    county: 'Nairobi',
    specialties: ['dermatology'],
    specialist_name: 'Dr. Grace Wanjiku',
    availability_status: 'Reported available',
    availability_note: 'Demo afternoon clinics on weekdays.',
    appointment_required: true,
    referral_required: false,
    contact_information: 'Demo contact: +254 700 000 201',
    instructions: 'Book an appointment before visiting. Do not send clinical photos to this demo.',
  },
  {
    id: 'prov-nbi-gp-01',
    facility_name: 'Parklands Family Demo Practice',
    facility_type: 'General practice',
    location: 'Parklands, Nairobi',
    county: 'Nairobi',
    specialties: ['general practice'],
    specialist_name: 'Dr. Peter Mwangi',
    availability_status: 'Reported available',
    availability_note: 'Walk-in demo hours shown for mornings.',
    appointment_required: false,
    referral_required: false,
    contact_information: 'Demo contact: +254 700 000 301',
    instructions: 'Walk-in possible during demo morning hours; appointments reduce wait time.',
  },
  {
    id: 'prov-nbi-gp-02',
    facility_name: 'Donholm Community Demo Health Post',
    facility_type: 'Community clinic',
    location: 'Donholm, Nairobi',
    county: 'Nairobi',
    specialties: ['general practice', 'pediatrics'],
    specialist_name: 'Clinical Officer Jane Achieng',
    availability_status: 'Reported available',
    availability_note: 'Demo data for common outpatient visits.',
    appointment_required: false,
    referral_required: false,
    contact_information: 'Demo contact: +254 700 000 302',
    instructions: 'Arrive early for same-day triage. Emergency cases should go to urgent care.',
  },
  {
    id: 'prov-nbi-maternal-01',
    facility_name: 'Mama Care Demo Maternity Clinic',
    facility_type: 'Maternal health clinic',
    location: 'Kileleshwa, Nairobi',
    county: 'Nairobi',
    specialties: ['maternal health'],
    specialist_name: 'Dr. Faith Njeri',
    availability_status: 'Reported available',
    availability_note: 'Antenatal demo clinics Tue/Thu.',
    appointment_required: true,
    referral_required: false,
    contact_information: 'Demo contact: +254 700 000 401',
    instructions: 'Bring your antenatal booklet if you have one. This is demonstration data only.',
  },
  {
    id: 'prov-nbi-ortho-01',
    facility_name: 'Motion Orthopedics Demo Hub',
    facility_type: 'Specialist clinic',
    location: 'Upper Hill, Nairobi',
    county: 'Nairobi',
    specialties: ['orthopedics'],
    specialist_name: 'Dr. Brian Ochieng',
    availability_status: 'Limited availability',
    availability_note: 'Demo wait times shown for non-urgent cases.',
    appointment_required: true,
    referral_required: true,
    contact_information: 'Demo contact: +254 700 000 501',
    instructions: 'Referral recommended for specialist review. Imaging may be requested at the facility.',
  },
  {
    id: 'prov-nbi-peds-01',
    facility_name: 'Little Steps Pediatrics Demo',
    facility_type: 'Specialist clinic',
    location: 'Karen, Nairobi',
    county: 'Nairobi',
    specialties: ['pediatrics'],
    specialist_name: 'Dr. Mercy Chebet',
    availability_status: 'Reported available',
    availability_note: 'Demo same-week appointments for routine visits.',
    appointment_required: true,
    referral_required: false,
    contact_information: 'Demo contact: +254 700 000 601',
    instructions: 'Bring the child\'s immunization card if available. Not for emergency care.',
  },
  {
    id: 'prov-msa-gp-01',
    facility_name: 'Nyali Coast Demo Family Clinic',
    facility_type: 'General practice',
    location: 'Nyali, Mombasa',
    county: 'Mombasa',
    specialties: ['general practice', 'dermatology'],
    specialist_name: 'Dr. Hassan Ali',
    availability_status: 'Reported available',
    availability_note: 'Demo weekday availability.',
    appointment_required: true,
    referral_required: false,
    contact_information: 'Demo contact: +254 700 000 701',
    instructions: 'Phone booking preferred. Synthetic data for demonstration only.',
  },
  {
    id: 'prov-ksm-cardio-01',
    facility_name: 'Lakeview Heart Demo Unit',
    facility_type: 'Hospital outpatient',
    location: 'Milimani, Kisumu',
    county: 'Kisumu',
    specialties: ['cardiology'],
    specialist_name: 'Dr. Esther Odhiambo',
    availability_status: 'Reported available',
    availability_note: 'Demo cardiology clinic twice weekly.',
    appointment_required: true,
    referral_required: true,
    contact_information: 'Demo contact: +254 700 000 801',
    instructions: 'Referral from a primary clinician is recommended in this demo scenario.',
  },
];

export function toProviderRow(record) {
  return {
    id: record.id,
    facilityName: record.facility_name,
    facilityType: record.facility_type,
    location: record.location,
    county: record.county,
    specialties: Array.isArray(record.specialties)
      ? record.specialties
      : String(record.specialties || '').split(',').map((s) => s.trim()).filter(Boolean),
    specialistName: record.specialist_name,
    availabilityStatus: record.availability_status,
    availabilityNote: record.availability_note,
    appointmentRequired: Boolean(record.appointment_required),
    referralRequired: Boolean(record.referral_required),
    contactInformation: record.contact_information,
    instructions: record.instructions,
    lastUpdated: record.last_updated || DEMO_LAST_UPDATED,
    lastUpdatedLabel: DEMO_LAST_UPDATED_LABEL,
    dataSource: record.data_source || DEMO_DATA_SOURCE,
    isDemoData: record.is_demo_data === undefined ? true : Boolean(record.is_demo_data),
  };
}
